---
title: "Untitled"
author: "Rochana Dudwadkar"
date: "8/21/2021"
output: html_document
---
```{r}
library(readr)
immunization_dpt <- read_csv("Immunization_Dpt.csv")
library(gdata)
```
```{r}
library(magrittr)
library(magrittr)
library(ggplot2)
library(lubridate)
library(tidyr)
library(dplyr)
data <- immunization_dpt
result <-data %>%
  pivot_longer(-c(`Country Name`, `Country Code`, `Indicator Name`, `Indicator Code`),
               names_to = "Year",
               values_to = "Count",
               values_drop_na = T)
```
```{r}
is.na(result)
immunization_dpt<-na.omit(result)
write.csv(immunization_dpt,"Immunization_Dpt.csv")
```


```{r}
library(readr)
govexp_primary <- read_csv("Government expenditure per student, primary (_ of GDP per capita).csv")
library(gdata)
```
```{r}
library(magrittr)
library(magrittr)
library(ggplot2)
library(lubridate)
library(tidyr)
library(dplyr)
data <- govexp_primary[-c(1,2,3,4),]
colnames(data) <- c("Country Name", "Country Code", "Indicator Name", "Indicator Code", "1998","1999","2000","2001","2002", "2003","2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020")
result <-data %>%
  pivot_longer(-c( `Country Name`, `Country Code`, `Indicator Name`, `Indicator Code`),
               names_to = "Year",
               values_to = "Count",
               values_drop_na = T)
```
```{r}
is.na(result)
govexp_primary<-na.omit(result)
write.csv(govexp_primary,"Government expenditure per student, primary (_ of GDP per capita).csv")
```


```{r}
library(readr)
immunization_measles <- read_csv("Immunization, measles (_ of children ages 12-23 months).csv")
library(gdata)
```
```{r}
library(magrittr)
library(magrittr)
library(ggplot2)
library(lubridate)
library(tidyr)
library(dplyr)
data <- immunization_measles[-c(1,2,3,4),-c(45)]
colnames(data) <- c("Country Name", "Country Code", "Indicator Name", "Indicator Code","1980", "1981", "1982","1983", "1984","1985","1986","1987","1988","1989","1990","1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998","1999","2000","2001","2002", "2003","2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")

immunization_measles <-result %>%
  pivot_longer(-c(`Country Name`, `Country Code`, `Indicator Name`, `Indicator Code`),
               names_to = "Year",
               values_to = "Count",
               values_drop_na = T)
```
```{r}
is.na(data)
result<-na.omit(data)
write.csv(immunization_measles,"Immunization, measles (_ of children ages 12-23 months).csv")
```


```{r}
library(readr)
anemia <- read_csv("Prevalence of anemia among children (_ of children ages 6-59 months).csv")
library(gdata)
```
```{r}
library(magrittr)
library(ggplot2)
library(lubridate)
library(tidyr)
library(dplyr)
data <- anemia[-c(1,2,3,4),-c(25)]
colnames(data) <- c("Country Name", "Country Code", "Indicator Name", "Indicator Code","2000","2001","2002", "2003","2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")

is.na(data)
result<-na.omit(data)
anemia <-result %>%
  pivot_longer(-c(`Country Name`, `Country Code`, `Indicator Name`, `Indicator Code`),
               names_to = "Year",
               values_to = "Count",
               values_drop_na = T)

write.csv(anemia,"Prevalence of anemia among children (_ of children ages 6-59 months).csv")

```


```{r}
library(readr)
overweight <- read_csv("Prevalence of overweight, weight for height (_ of children under 5).csv")
library(gdata)
```
```{r}
library(ggplot2)
library(lubridate)
library(tidyr)
library(dplyr)
data <- overweight[-c(1,2,3,4),]
colnames(data) <- c("Country Name", "Country Code", "Indicator Name", "Indicator Code","1986","1987","1988","1989","1990","1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998","1999","2000","2001","2002", "2003","2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019","2020")

result<-data %>%
  pivot_longer(-c(`Country Name`, `Country Code`, `Indicator Name`, `Indicator Code`),
               names_to = "Year",
               values_to = "Count",
               values_drop_na = T)
is.na(data)
overweight<-na.omit(result)

write.csv(overweight,"Prevalence of overweight, weight for height (_ of children under 5).csv")
```

```{r}
library(readr)
stunting <- read_csv("Prevalence of stunting, height for age (_ of children under 5).csv")
library(gdata)
```
```{r}
library(ggplot2)
library(lubridate)
library(tidyr)
library(dplyr)
data <- stunting[-c(1,2,3,4),]
colnames(data) <- c("Country Name", "Country Code", "Indicator Name", "Indicator Code","1987","1988","1989","1990","1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998","1999","2000","2001","2002", "2003","2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019","2020")

result<-data %>%
  pivot_longer(-c(`Country Name`, `Country Code`, `Indicator Name`, `Indicator Code`),
               names_to = "Year",
               values_to = "Count",
               values_drop_na = T)
is.na(data)
stunting<-na.omit(result)
write.csv(stunting,"Prevalence of stunting, height for age (_ of children under 5).csv")
```


```{r}
library(readr)
underweight <- read_csv("Prevalence of underweight, weight for age (_ of children under 5).csv")
library(gdata)
```
```{r}
library(ggplot2)
library(lubridate)
library(tidyr)
library(dplyr)
data <- underweight[-c(1,2,3,4),]
colnames(data) <- c("Country Name", "Country Code", "Indicator Name", "Indicator Code","1986","1987","1988","1989","1990","1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998","1999","2000","2001","2002", "2003","2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019","2020")

result<-data %>%
  pivot_longer(-c(`Country Name`, `Country Code`, `Indicator Name`, `Indicator Code`),
               names_to = "Year",
               values_to = "Count",
               values_drop_na = T)

is.na(data)
underweight<-na.omit(result)
write.csv(underweight,"Prevalence of underweight, weight for age (_ of children under 5).csv")
```


```{r}
library(readr)
wasting <- read_csv("Prevalence of wasting, weight for height (_ of children under 5).csv")
library(gdata)
```
```{r}
library(ggplot2)
library(lubridate)
library(tidyr)
library(dplyr)
data <- wasting[-c(1,2,3,4),]
colnames(data) <- c("Country Name", "Country Code", "Indicator Name", "Indicator Code","1987","1988","1989","1990","1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998","1999","2000","2001","2002", "2003","2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019","2020")

result<-data %>%
  pivot_longer(-c(`Country Name`, `Country Code`, `Indicator Name`, `Indicator Code`),
               names_to = "Year",
               values_to = "Count",
               values_drop_na = T)

is.na(data)
wasting<-na.omit(result)
write.csv(wasting,"Prevalence of wasting, weight for height (_ of children under 5).csv")
```


```{r}
library(readr)
immunization_dpt <- read_csv("Immunization_Dpt.csv")
govexp_primary <- read_csv("Government expenditure per student, primary (_ of GDP per capita).csv")
immunization_measles <- read_csv("Immunization, measles (_ of children ages 12-23 months).csv")
anemia <- read_csv("Prevalence of anemia among children (_ of children ages 6-59 months).csv")
overweight <- read_csv("Prevalence of overweight, weight for height (_ of children under 5).csv")
stunting <- read_csv("Prevalence of stunting, height for age (_ of children under 5).csv")
underweight <- read_csv("Prevalence of underweight, weight for age (_ of children under 5).csv")
wasting <- read_csv("Prevalence of wasting, weight for height (_ of children under 5).csv")
```
```{r}
#merging two dataframes
Total <- rbind(anemia, govexp_primary,immunization_dpt, immunization_measles, overweight, stunting, underweight, wasting)

```




