---
title: "Women health"
author: "Rochana Dudwadkar"
date: "8/22/2021"
output: html_document
---

```{r}
library(readr)
adolescents <- read_csv("1.csv")
library(gdata)
```
```{r}
library(magrittr)
library(magrittr)
library(ggplot2)
library(lubridate)
library(tidyr)
library(dplyr)
```
```{r}
data <- adolescents[-c(1,2,3,4),]
colnames(data) <- c("Country Name", "Country Code", "Indicator Name", "Indicator Code","1960", "1961", "1962","1963", "1964","1965","1966","1967","1968","1969", "1970", "1971", "1972","1973", "1974","1975","1976","1977","1978","1979", "1980", "1981", "1982","1983", "1984","1985","1986","1987","1988","1989","1990","1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998","1999","2000","2001","2002", "2003","2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")
```
```{r}
result <-data %>%
  pivot_longer(-c(`Country Name` , `Country Code`, `Indicator Name`, `Indicator Code`),
               names_to = "Year",
               values_to = "Count",
               values_drop_na = T)
```
```{r}
is.na(result)
adolescents<-na.omit(result)
write_csv(adolescents,"Adolescent fertility rate (births per 1,000 women ages 15-19).csv")
```


```{r}
library(readr)
antiretroviral <- read_csv("2.csv")
library(gdata)
```
```{r}
library(magrittr)
library(magrittr)
library(ggplot2)
library(lubridate)
library(tidyr)
library(dplyr)
```
```{r}
data <- antiretroviral[-c(1,2,3,4),-25]
colnames(data) <- c("Country Name", "Country Code", "Indicator Name", "Indicator Code", "2000","2001","2002", "2003","2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")
```
```{r}
result <-data %>%
  pivot_longer(-c(`Country Name` , `Country Code`, `Indicator Name`, `Indicator Code`),
               names_to = "Year",
               values_to = "Count",
               values_drop_na = T)
```
```{r}
is.na(result)
antiretroviral<-na.omit(result)
write.csv(antiretroviral,"Antiretroviral therapy coverage for PMTCT (_ of pregnant women living with HIV).csv")
```

```{r}
library(readr)
mortality_rate <- read_csv("3.csv")
library(gdata)
```
```{r}
library(magrittr)
library(magrittr)
library(ggplot2)
library(lubridate)
library(tidyr)
library(dplyr)
```
```{r}
data <- mortality_rate[-c(1,2,3,4),]
colnames(data) <- c("Country Name", "Country Code", "Indicator Name", "Indicator Code", "1960", "1961", "1962","1963", "1964","1965","1966","1967","1968","1969", "1970", "1971", "1972","1973", "1974","1975","1976","1977","1978","1979", "1980", "1981", "1982","1983", "1984","1985","1986","1987","1988","1989","1990","1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998","1999","2000","2001","2002", "2003","2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")
```
```{r}
result <-data %>%
  pivot_longer(-c(`Country Name` , `Country Code`, `Indicator Name`, `Indicator Code`),
               names_to = "Year",
               values_to = "Count",
               values_drop_na = T)
```
```{r}
is.na(result)
mortality_rate<-na.omit(result)
write.csv(mortality_rate,"Mortality rate, adult, female (per 1,000 female adults).csv")
```


```{r}
library(readr)
pregnant_care <- read_csv("4.csv")
library(gdata)
```
```{r}
library(magrittr)
library(magrittr)
library(ggplot2)
library(lubridate)
library(tidyr)
library(dplyr)
```
```{r}
data <- pregnant_care[-c(1,2,3,4),]
colnames(data) <- c("Country Name", "Country Code", "Indicator Name", "Indicator Code", "1990","1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998","1999","2000","2001","2002", "2003","2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020")
```
```{r}
result <-data %>%
  pivot_longer(-c(`Country Name` , `Country Code`, `Indicator Name`, `Indicator Code`),
               names_to = "Year",
               values_to = "Count",
               values_drop_na = T)
```
```{r}
is.na(result)
pregnant_care<-na.omit(result)
write.csv(pregnant_care,"Pregnant women receiving prenatal care (_).csv")
```


```{r}
library(readr)
anemia <- read_csv("5.csv")
library(gdata)
```
```{r}
library(magrittr)
library(magrittr)
library(ggplot2)
library(lubridate)
library(tidyr)
library(dplyr)
```
```{r}
data <- anemia[-c(1,2,3,4),-25]
colnames(data) <- c("Country Name", "Country Code", "Indicator Name", "Indicator Code","2000","2001","2002", "2003","2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020")
```
```{r}
result <-data %>%
  pivot_longer(-c(`Country Name` , `Country Code`, `Indicator Name`, `Indicator Code`),
               names_to = "Year",
               values_to = "Count",
               values_drop_na = T)
```
```{r}
is.na(result)
anemia<-na.omit(result)
write.csv(anemia,"Prevalence of anemia among women of reproductive age (_ of women ages 15-49).csv")
```


```{r}
library(readr)
seats_women <- read_csv("6.csv")
library(gdata)
```
```{r}
library(magrittr)
library(magrittr)
library(ggplot2)
library(lubridate)
library(tidyr)
library(dplyr)
```
```{r}
data <- seats_women[-c(1,2,3,4),]
colnames(data) <- c("Country Name", "Country Code", "Indicator Name", "Indicator Code","1997", "1998", "1999", "2000","2001","2002", "2003","2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020")
```
```{r}
result <-data %>%
  pivot_longer(-c(`Country Name` , `Country Code`, `Indicator Name`, `Indicator Code`),
               names_to = "Year",
               values_to = "Count",
               values_drop_na = T)
```
```{r}
is.na(result)
seats_women<-na.omit(result)
write.csv(seats_women,"Proportion of seats held by women in national parliaments (_).csv")
```


```{r}
library(readr)
hiv <- read_csv("7.csv")
library(gdata)
```
```{r}
library(magrittr)
library(magrittr)
library(ggplot2)
library(lubridate)
library(tidyr)
library(dplyr)
```
```{r}
data <- hiv[-c(1,2,3,4),]
colnames(data) <- c("Country Name", "Country Code", "Indicator Name", "Indicator Code","1990","1991", "1992", "1993", "1994", "1995", "1996","1997", "1998", "1999", "2000","2001","2002", "2003","2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019")
```
```{r}
result <-data %>%
  pivot_longer(-c(`Country Name` , `Country Code`, `Indicator Name`, `Indicator Code`),
               names_to = "Year",
               values_to = "Count",
               values_drop_na = T)
```
```{r}
is.na(result)
hiv<-na.omit(result)
write.csv(hiv,"Women_s share of population ages 15+ living with HIV (_).csv")
```



